services:
  postgres:
    image: postgres:17
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrations:
    image: migrate/migrate
    env_file:
      - ../.env
    volumes:
      - .././migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable",
      "up"
    ]
    depends_on:
      - postgres

volumes:
  db_data:
