services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    env_file:
      - .env.example
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped


  postgres:
    image: postgres:17
    env_file:
      - .env.example
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      retries: 5

  migrations:
    image: migrate/migrate
    env_file:
      - .env.example
    volumes:
      - ./migrations:/migrations
    command: >
      -path /migrations
      -database ${POSTGRES_DSN}
      up
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable"
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "9187:9187"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus:ro
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - service


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  db_data:
