services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped


  postgres:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      retries: 5

  migrations:
    image: migrate/migrate
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    command: >
      -path /migrations
      -database ${POSTGRES_DSN}
      up
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

volumes:
  db_data:
